MAX_REQUESTS_SYMBOLS = 300  # Максимально количество символов на один запрос
MAX_USER_TTS_SYMBOLS = 2000  # Максимально количество символов для озвучки текста на пользователя
TEXT_VOICE = ""  # marina or madirus
"""Поскольку вы на вебинаре сказали, что неудобно проверять с .env, то пишем все секретные данные в конфиге))"""

BOT_TOKEN = ""  # 6565406578:AAHJXXP9C3Y...
iam_token = ""  # t1.9euelZrMmpmVi4vJyYqai5iVksnIl-3rnpWajM...
folder_id = ""  # b1gpkb6...
